import os
import sys
from CeleryPy import log
import Capture 
import Image

Image.capture()
log(getcoordinates(), message_type='error', title='FUNCO')

